#include <stdio.h>
#include <stdlib.h>

#define TOKEN_TYPE_SKIPABLE_LOOKUP_GENERATOR
#include "token_type_c.h"

int is_token_in_token_type_skipable(TokenType_C type)
{
    for (size_t i = 0; i < TOKEN_TYPE_SKIPABLE_SIZE; ++i) {
        if (type == token_type_skipable[i]) {
            return 1;
        }
    }

    return 0;
}

int main(void)
{
    printf("// generated by: tools/token_type_skipable_lookup_generator\n");
    printf("const int token_type_skipable_lookup[TOKEN_TYPE_C_LENGTH] = {\n");
    
    for (TokenType_C type = 0; type < TOKEN_TYPE_C_LENGTH; ++type) {
        if (is_token_in_token_type_skipable(type)) {
            printf("\t1");
        } else {
            printf("\t0");
        }
        
        if (type != TOKEN_TYPE_C_LENGTH - 1) {
            printf(",");
        }
        
        printf("\n");
    }
    
    printf("};\n");
    
    return EXIT_SUCCESS;
}
